"""
Decision logger — writes every research result to disk and (eventually) GitHub.
Each decision gets its own markdown file in decisions/.
"""

import json
import os
from datetime import datetime
from pathlib import Path

from src.research.researcher import ResearchResult

DECISIONS_DIR = Path(__file__).parent.parent.parent / "decisions"


class DecisionLogger:
    def __init__(self, decisions_dir: Path = DECISIONS_DIR):
        self.dir = decisions_dir
        self.dir.mkdir(exist_ok=True)

    def log(self, result: ResearchResult) -> Path:
        """Write a decision to disk. Returns the path of the file."""
        date_str = datetime.utcnow().strftime("%Y-%m-%d")
        safe_q = result.question[:60].replace("/", "-").replace(" ", "_")
        filename = f"{date_str}_{result.market_id}_{safe_q}.md"
        path = self.dir / filename

        action = "BET_YES" if result.edge > 0 and result.should_bet else \
                 "BET_NO" if result.edge < 0 and result.should_bet else "PASS"

        content = f"""# Decision Log

**Date:** {result.timestamp}
**Market ID:** {result.market_id}
**Question:** {result.question}

## Verdict: {action}

| Field | Value |
|-------|-------|
| Market YES price | {result.market_yes_price:.1%} |
| Polly YES estimate | {result.polly_yes_prob:.1%} |
| Edge | {result.edge:+.1%} |
| Confidence | {result.confidence:.0%} |
| Recommended bet size | {result.bet_size_pct:.1%} of bankroll |

## Reasoning

{result.reasoning}

## Sources

{chr(10).join(f'- {s}' for s in result.sources) if result.sources else '- (none)'}

---
*Generated by Polly 🦉*
"""
        path.write_text(content)
        print(f"📝 Logged: {path.name}")
        return path

    def log_scan_summary(self, results: list[ResearchResult]) -> Path:
        """Write a summary of a full scan."""
        date_str = datetime.utcnow().strftime("%Y-%m-%d_%H%M%S")
        path = self.dir / f"scan_{date_str}.md"

        bets = [r for r in results if r.should_bet]
        passes = [r for r in results if not r.should_bet]

        lines = [
            f"# Scan Summary — {date_str}\n",
            f"**Markets analyzed:** {len(results)}  |  "
            f"**Bets flagged:** {len(bets)}  |  "
            f"**Passed:** {len(passes)}\n\n",
            "## Opportunities\n\n" if bets else "## No opportunities this scan.\n\n",
        ]

        for r in bets:
            lines.append(r.summary() + "\n")

        lines.append("\n## All Markets Reviewed\n\n")
        for r in results:
            lines.append(r.summary() + "\n")

        path.write_text("".join(lines))
        print(f"📊 Scan summary: {path.name}")
        return path

    def load_all(self) -> list[dict]:
        """Load all decision logs as dicts."""
        results = []
        for f in sorted(self.dir.glob("*.json")):
            try:
                results.append(json.loads(f.read_text()))
            except Exception:
                pass
        return results
